services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=park.it
    volumes:
      - park.it-data:/bitnami/postgresql

volumes:
  park.it-data:
